# Generated by Django 5.1 on 2024-10-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_venta_ventas_remove_producto_etiquetas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha_venta',
            field=models.DateField(auto_now_add=True),
        ),
    ]
